.PHONY: all address bsgs kangaroo clean

all: address bsgs kangaroo

address:
	$(MAKE) -C Address

bsgs:
	$(MAKE) -C BSGS

kangaroo:
	$(MAKE) -C kangaroo

clean:
	$(MAKE) -C Address clean
	$(MAKE) -C BSGS clean
	$(MAKE) -C kangaroo clean
